### ISSUE TITLE
wildcard rules are not reusable

### ISSUE THREAD

**Issue by cainlevy** [dimatill/graphql-shield#1358]
# Bug report

- [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

Wildcard rules appear to not be reusable.

1. For example, I might define a policy like `const allowAll = { '*': allow }` and try to use it for multiple types. This will not work.
2. I might also try to define static permissions and then apply them to multiple server instances (in tests). This will not work.

## To Reproduce

Steps to reproduce the behavior, please provide code snippets or a repository:

1. This is my GraphQL Schema.

```graphql
type Query {
  book: Book!
  author: Author!
}

type Book {
  id: ID!
}

type Author {
  id: ID!
}
```

2. This is the invoked query

```graphql
query {
  book { id }
  author { id }
}
```

3. I use these permissions

```ts
const allowAll = { '*': allow };
const permissions = shield({
  Query: allowAll,
  Book: allowAll,
  Author: allowAll,
}, { fallbackRule: deny })
```

4. This is the error I see

```ts
Not authorised!
```

## Expected behavior

Success

## Actual behaviour

Authorization failure

## Additional context

https://github.com/maticzav/graphql-shield/issues/1341#issuecomment-969462820

**Comment by cainlevy** [comment]
I respect your push to get this library sponsored and I hope it's successful!

I'm having a tough time getting started because of this bug, however, plus some other usability concerns that I haven't been able to explore because of the investment I've sunk into debugging the library.

**Comment by hamxabaig** [comment]
I'm getting exactly the same issue mentioned by @cainlevy, weird thing is that it seems to run the resolver but still throws "Not authorised" error.
