### ISSUE TITLE
NPM release with recent changes

### ISSUE THREAD

**Issue by hayksaryan** [dimatill/graphql-shield#1453]
- [x] I have checked existing issue and found none that could answer my question.

When will the new NPM release happen? Will it happen? For example graphql version 16 support is something we're looking forward to receive. We'd want to keep using `graphql-shield` untill we get some time to migrate from it to more maintained options.

**Comment by hayksaryan** [comment]
@dimatill @maticzav

**Comment by dimatill** [comment]
@hayksaryan it will happen. we're working on it. it should happen either this week or in a few weeks

**Comment by hayksaryan** [comment]
Thanks for the information 🙏

**Comment by dimatill** [comment]
recent changes were released. graphql v16 support is there
