### ISSUE TITLE
Documentation website down

### ISSUE THREAD

**Issue by Tom-Pearce** [dimatill/graphql-shield#1490]
# Bug report

- [x] I have checked other issues to make sure this is not a duplicate.

## Describe the bug

Documentation site down

## To Reproduce

Visit https://graphql-shield.vercel.app/ as detailed in the readme

## Expected behaviour

Documentation website

## Actual behaviour

404
![Screenshot 2022-11-14 at 11 33 15](https://user-images.githubusercontent.com/33258637/201649871-5442bcc9-c8f2-46fc-a9da-e21ee0c29659.png)

**Comment by saihaj** [comment]
the official website is hosted under `https://the-guild.dev/graphql/shield` or `https://graphql-sheild.com`
